Transform: AWS::Serverless-2016-10-31
Metadata:
  AWS::ServerlessRepo::Application:
    Name: AthenaUserDefinedFunctions
    Description: This connector enables Amazon Athena to leverage common UDFs made
      available via Lambda.
    Author: default author
    SpdxLicenseId: Apache-2.0
    LicenseUrl: s3://tmae-s3-demo-1/34400b68072d710fecd0a2940a0d1658
    ReadmeUrl: s3://tmae-s3-demo-1/54fb1a1e256f0578500783d118e03d05
    Labels:
    - athena-federation
    HomePageUrl: https://github.com/awslabs/aws-athena-query-federation
    SemanticVersion: 2022.46.1
    SourceCodeUrl: https://github.com/awslabs/aws-athena-query-federation
Parameters:
  LambdaFunctionName:
    Description: The name you will give to Lambda function which executes your UDFs.
      This name must satisfy the pattern ^[a-z0-9-_]{1,64}$
    Type: String
    AllowedPattern: ^[a-z0-9-_]{1,64}$
  LambdaTimeout:
    Description: Maximum Lambda invocation runtime in seconds. (min 1 - 900 max)
    Default: 900
    Type: Number
  LambdaMemory:
    Description: Lambda memory in MB (min 128 - 3008 max).
    Default: 3008
    Type: Number
  SecretNameOrPrefix:
    Description: The name or prefix of a set of names within Secrets Manager that
      this function should have access to. (e.g. database-*).
    Type: String
Resources:
  ConnectorConfig:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName:
        Ref: LambdaFunctionName
      Handler: com.amazonaws.athena.connectors.udfs.AthenaUDFHandler
      CodeUri: s3://tmae-s3-demo-1/3a61ded720ee93542d69681ef7edea6b
      Description: This connector enables Amazon Athena to leverage common UDFs made
        available via Lambda.
      Runtime: java11
      Timeout:
        Ref: LambdaTimeout
      MemorySize:
        Ref: LambdaMemory
      Policies:
      - Statement:
        - Action:
          - secretsmanager:GetSecretValue
          Effect: Allow
          Resource:
            Fn::Sub: arn:${AWS::Partition}:secretsmanager:*:*:secret:${SecretNameOrPrefix}
        Version: '2012-10-17'
    Metadata:
      SamResourceId: ConnectorConfig
